name: Bloom
options:
  bundleIdPrefix: com.ajaypalnitj
settings:
  base:
    PRODUCT_NAME: Bloom
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SDKROOT: iphoneos
    SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
    TARGETED_DEVICE_FAMILY: "1,2"
    GENERATE_INFOPLIST_FILE: YES
targets:
  Bloom:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources: 
      - path: Bloom
    info:
      path: Bloom/Info.plist
      properties:
        CFBundleDisplayName: "Bloom"
        UILaunchScreen:
          UIColorName: LaunchBackgroundColor
          UIImageName: SplashIcon
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortraitUpsideDown
        NSCameraUsageDescription: "Bloom needs camera access to capture your daily zen moments."
        NSMicrophoneUsageDescription: "Bloom needs microphone access to record ambient sounds."
        NSPhotoLibraryAddUsageDescription: "Bloom needs access to save your weekly Zen video."
        NSPhotoLibraryUsageDescription: "Bloom needs access to your photos to save videos."
schemes:
  Bloom:
    build:
      targets:
        Bloom: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
